name: "app"

type: "python:3.9"

disk: 6144

resources:
  base_memory: 1024
  memory_ratio: 1024

dependencies:
  python3:
    pipenv: "2021.5.29"

web:
  upstream:
    socket_family: unix
  commands:
    start: |
      WORKERS="$(jq ".info.limits.memory / 250 | tonumber | floor" /run/config.json)"
      blackfire-python gunicorn app.main:app -b unix:$SOCKET -w ${WORKERS} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"
  locations:
    "/static":
      root: "static"
      rules:
        '\.(css|js|ico)$':
          expires: 10m

mounts:
  "logs":
    source: local
    source_path: logs
  "user_training_data":
    source: local
    source_path: user_training_data

hooks:
  build: |
    set -e
    pipenv install --system --deploy
    pipenv run /opt/python/3.9/bin/python3.9 -m pip install blackfire==1.8.0
    pipenv run /opt/python/3.9/bin/python3.9 -m spacy download en_core_web_sm
    pipenv run /opt/python/3.9/bin/python3.9 -m spacy download de_core_news_sm
    pipenv run pybabel compile -d locales -l de_DE -f
    pipenv run pybabel compile -d locales -l en_GB -f

relationships:
  languagetool: "languagetool:http"
  rediscache: "cacheredis:redis"

variables:
  env:
    BLACKFIRE_AGENT_SOCKET: "unix:///run/blackfire.sock"
    BLACKFIRE_LOG_FILE: "/tmp/blackfire.log"

crons:
  generate-statistics:
    spec: "55 0 * * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = main ]; then
          php send_statistics.php
      fi
