name: 'app'

type: 'python:3.8'

disk: 3072

resources:
  base_memory: 1024
  memory_ratio: 1024

dependencies:
  python3:
    pipenv: '2021.5.29'

web:
  upstream:
    socket_family: unix
  commands:
    start: |
      [ $PLATFORM_ENVIRONMENT_TYPE == "development" ] && WORKERS="6" || WORKERS="$(jq ".info.limits.memory / 250 | tonumber | floor" /run/config.json)"
      gunicorn app.main:app -b unix:$SOCKET -w ${WORKERS} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"
  locations:
    '/':
      passthru: true

mounts:
  'files':
    source: local
    source_path: files
  'logs':
    source: local
    source_path: logs

hooks:
  build: |
    set -e
    pipenv install --system --deploy
    pipenv run /opt/python/3.8/bin/python3.8 -m spacy download en_core_web_sm
    pipenv run /opt/python/3.8/bin/python3.8 -m spacy download de_core_news_sm
    pipenv run pybabel compile -d locales -l de_DE -f
    pipenv run pybabel compile -d locales -l en_GB -f

relationships:
  languagetool: "languagetool:http"