[tool.pdm]
[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[tool.pdm.dev-dependencies]
dev = [
    "click",
    "polib",
    "pytest",
    "pytest-cov",
    "python-dotenv",
    "black",
    "opencensus-ext-azure",
    "pytest-asyncio",
    "pytest-snapshot",
    "pytest-env>=0.8.1",
    "httpx>=0.25.0",
]

[project]
name = "witty-works"
version = "2.0"
description = ""
authors = [
    {name = "Lukas Kahwe Smith", email = "lukas.smith@witty.works"},
]
dependencies = [
    "fastapi<0.110.0,>=0.109.0",
    "pydantic<3.0.0,>=2.0.0",
    "pydantic-settings>=2.0.3",
    "uvicorn[standard]",
    "gunicorn",
    "spacy",
    "pandas",
    "aiofiles",
    "babel",
    "aiohttp",
    "sentry-sdk",
    "opencensus-ext-azure",
    "redis",
    "platformshconfig",
    "fakeredis",
    "fasttext-wheel",
    "slack-bolt",
    "german-nouns",
    "inflex",
    "spacy-lookups-data",
    "en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl",
    "de-core-news-lg @ https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-3.7.0/de_core_news_lg-3.7.0-py3-none-any.whl",
    "secure>=0.3.0",
    "spacymoji>=3.0.1",
    "emoji>=0.6.0",
    "cmp-version>=3.0.0",
    "python-jose>=3.3.0",
    "eng>=0.1.1",
    "blackfire<1.20.0,>=1.19.0",
    "blackfire-conprof>=1.0.0",
    "aiosqlite>=0.19.0",
    "Pyarrow>=15.0.0",
]
requires-python = ">3.12"
license = "Proprietary"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
