sonar.projectKey=witty-works_nlp_api
sonar.organization=witty-works

sonar.python.version=3.9
sonar.source=app
sonar.source=bin
sonar.tests=tests
sonar.coverage.exclusions=bin
sonar.python.coverage.reportPaths=coverage.xml