
[supervisord]
logfile=/tmp/supervisord.log
nodaemon=true
minfds=1024
pidfile=/tmp/supervisord.pid

[program:gunicorn]
command=gunicorn app.main:app -b unix:/run/app.sock -w 12 -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*" --timeout 120
autostart=true
autorestart=true

[program:blackfire-agent]
command=/usr/bin/blackfire-agent --config=/etc/blackfire-conf/agent --socket=tcp://127.0.0.1:8307 --log-level=5 --log-file=/tmp/log/app.log
autostart=true
autorestart=true
