categories = {
    "abbreviation": {
        "inclusive": False,
        "category": "style",
        "gravity": 3,
        "importance": 3,
    },
    "ability": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "ableism": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
    "age": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "age_in_jobs": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "age_old": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "age_young": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "agentic": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "americanism": {
        "inclusive": False,
        "category": "style",
        "gravity": 3,
        "importance": 3,
    },
    "antimuslim": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
    "antisemitism": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
    "behavior": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "belief": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "binary_pronouns": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "classism": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "cognitive_ability": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "cognitive_perception": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "communal": {
        "inclusive": True,
        "category": "inclusive",
        "gravity": None,
        "importance": 2,
    },
    "corporate_rules": {
        "inclusive": False,
        "category": "corporate_rules",
        "gravity": 3,
        "importance": None,
    },
    "culture": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "d_and_i": {
        "inclusive": True,
        "category": "inclusive",
        "gravity": None,
        "importance": 2,
    },
    "education": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "ethnicity": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "exaggerating": {
        "inclusive": False,
        "category": "style",
        "gravity": 2,
        "importance": 2,
    },
    "female_stereotype": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "filler": {"inclusive": False, "category": "style", "gravity": 3, "importance": 3},
    "formality": {
        "inclusive": False,
        "category": "style",
        "gravity": 3,
        "importance": 3,
    },
    "function": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "gen_boomer": {
        "inclusive": False,
        "category": "style",
        "gravity": 3,
        "importance": 3,
    },
    "gen_z": {"inclusive": False, "category": "style", "gravity": 3, "importance": 3},
    "gender_identity": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "gendered": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "gendered_denominations_ending": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "hearing": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "hidden_image": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "hollow": {"inclusive": False, "category": "style", "gravity": 3, "importance": 3},
    "homophobia": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
    "inclusive": {
        "inclusive": True,
        "category": "inclusive",
        "gravity": None,
        "importance": 2,
    },
    "job_requirements": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "leadership": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "learning": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "male_stereotype": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "medical_state": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "mental_wellbeing": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "migration": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "military_source": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "misgendering_institutions": {
        "inclusive": False,
        "category": "style",
        "gravity": 3,
        "importance": 3,
    },
    "mobility": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "openly_discriminating": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 3,
        "importance": None,
    },
    "orthography": {
        "inclusive": False,
        "category": "orthography",
        "gravity": 1,
        "importance": 1,
    },
    "overload": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "passive_voice": {
        "inclusive": False,
        "category": "style",
        "gravity": 3,
        "importance": 3,
    },
    "pressure": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "racism": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
    "racist_source": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "salary_vague": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "sexism": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
    "sexual_orientation": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "speech": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "sports_terms": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "style": {"inclusive": False, "category": "style", "gravity": 3, "importance": 3},
    "technical_frameworks": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "titles": {
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
        "importance": 2,
    },
    "transphobia": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
    "unconscious_bias": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "verbose": {"inclusive": False, "category": "style", "gravity": 3, "importance": 3},
    "vision": {
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
        "importance": 2,
    },
    "workload": {
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 3,
        "importance": None,
    },
    "xenophobia": {
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
        "importance": 1,
    },
}
