categories = {
    "gendered": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "titles": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "function": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "leadership": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "hidden_image": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "gendered_denominations_ending": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "style": {"color": "blue", "inclusive": False, "category": "style", "gravity": 3},
    "passive_voice": {
        "color": "blue",
        "inclusive": False,
        "category": "style",
        "gravity": 3,
    },
    "misgendering_institutions": {
        "color": "blue",
        "inclusive": False,
        "category": "style",
        "gravity": 3,
    },
    "unconscious_bias": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "agentic": {
        "color": "brown",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "inclusive": {
        "color": "green",
        "inclusive": True,
        "category": "inclusive",
        "gravity": 2,
    },
    "communal": {
        "color": "green",
        "inclusive": True,
        "category": "inclusive",
        "gravity": 2,
    },
    "d_and_i": {
        "color": "green",
        "inclusive": True,
        "category": "inclusive",
        "gravity": 2,
    },
    "hollow": {"color": "blue", "inclusive": False, "category": "style", "gravity": 3},
    "filler": {"color": "blue", "inclusive": False, "category": "style", "gravity": 3},
    "job_requirements": {
        "color": "brown",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "salary_vague": {
        "color": "blue",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "abbreviation": {
        "color": "blue",
        "inclusive": False,
        "category": "style",
        "gravity": 4,
    },
    "verbose": {"color": "blue", "inclusive": False, "category": "style", "gravity": 5},
    "exaggerating": {
        "color": "blue",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "binary_pronouns": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "age": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "age_old": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "age_young": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "culture": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "migration": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "sexual_orientation": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "gender_identity": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "racist_source": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "classism": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "belief": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "female_stereotype": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "male_stereotype": {
        "color": "yellow",
        "inclusive": False,
        "category": "gendered",
        "gravity": 2,
    },
    "gen_boomer": {
        "color": "blue",
        "inclusive": False,
        "category": "style",
        "gravity": 3,
    },
    "gen_z": {"color": "blue", "inclusive": False, "category": "style", "gravity": 3},
    "orthography": {
        "color": "blue",
        "inclusive": False,
        "category": "style",
        "gravity": 3,
    },
    "overload": {
        "color": "brown",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "education": {
        "color": "orange",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "workload": {
        "color": "brown",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "ethnicity": {
        "color": "orange",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "age_in_jobs": {
        "color": "orange",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "technical_frameworks": {
        "color": "orange",
        "inclusive": False,
        "category": "job_requirements",
        "gravity": 5,
    },
    "corporate_rules": {
        "color": "blue",
        "inclusive": False,
        "category": "corporate_rules",
        "gravity": 2,
    },
    "americanism": {
        "color": "blue",
        "inclusive": False,
        "category": "style",
        "gravity": 3,
    },
    "pressure": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "visual_impairment": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "medical_condition": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "intellectual_impairment": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "hearing_speech_impairment": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "mobility_impairment": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "mental_impairment": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "ability": {
        "color": "orange",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2,
    },
    "formality": {
        "color": "blue",
        "inclusive": False,
        "category": "style",
        "gravity": 3,
    },
    "openly_discriminating": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
    "racism": {"color": "brown", "inclusive": False, "category": "", "gravity": 1},
    "sexism": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
    "transphobia": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
    "homophobia": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
    "antisemitism": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
    "antimuslim": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
    "xenophobia": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
    "ableism": {
        "color": "brown",
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1,
    },
}
