categories = {
    "abbreviation": {
        "why": True,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "😉",
    },
    "ability": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "ableism": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "age": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "🤔",
    },
    "age_old": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "age_young": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "agentic": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "anglicism": {
        "why": True,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 2,
        "emoji": "😉",
    },
    "antimuslim": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "antisemitism": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "behavior": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "belief": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "binary_pronouns": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "casing": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "❌",
    },
    "classism": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "cognitive_ability": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "cognitive_perception": {
        "why": False,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "color": {
        "why": "en",
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
    },
    "communal": {
        "why": True,
        "inclusive": True,
        "category": "inclusive",
        "gravity": None,
        "importance": 2,
        "emoji": "✅",
    },
    "compounding": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "⚠️",
    },
    "confused_words": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "❌",
    },
    "corporate_rules": {
        "why": False,
        "inclusive": False,
        "category": "corporate_rules",
        "gravity": 0.9,
        "importance": 1,
    },
    "culture": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "d_and_i": {
        "why": True,
        "inclusive": True,
        "category": "inclusive",
        "gravity": None,
        "importance": 3,
        "emoji": "✅",
    },
    "emotional_security": {
        "why": False,
        "inclusive": True,
        "category": "inclusive",
        "gravity": None,
        "importance": 3,
        "emoji": "✅",
    },
    "exaggerating": {
        "why": True,
        "inclusive": False,
        "category": "style",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😮\u200d💨",
    },
    "false_friends": {
        "why": False,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "🤔",
    },
    "female_stereotype": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "filler": {
        "why": True,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 2,
        "emoji": "😟",
    },
    "formality": {
        "why": True,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "🧊",
    },
    "function": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "💡",
    },
    "gender_identity": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "gender_specific_abbreviation": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😮",
    },
    "gendered": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "gendered_denominations_ending": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "💯",
    },
    "general_style": {
        "why": False,
        "inclusive": False,
        "category": "style",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "🤔",
    },
    "generic_plural": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "😮",
    },
    "grammar": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "❌",
    },
    "hearing": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "hidden_image": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "hollow": {
        "why": True,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "🙄",
    },
    "homophobia": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "inclusive": {
        "why": False,
        "inclusive": True,
        "category": "inclusive",
        "gravity": None,
        "importance": 3,
        "emoji": "✅",
    },
    "leadership": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "learning": {
        "why": False,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "male_stereotype": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "medical_state": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "mental_wellbeing": {
        "why": False,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "migration": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "military_source": {
        "why": False,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "🪖",
    },
    "misc": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "🤔",
    },
    "mobility": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "offensive_language": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "openly_discriminating": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "orthography": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "❌",
    },
    "punctuation": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "❌",
    },
    "racism": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "racist_source": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "redundancy": {
        "why": False,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "🤔",
    },
    "regionalisms": {
        "why": False,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "🤔",
    },
    "repetitions": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "⚠️",
    },
    "repetitions_style": {
        "why": False,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "😟",
    },
    "semantics": {
        "why": False,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "🤔",
    },
    "sexism": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "sexual_orientation": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "simple_language": {
        "why": False,
        "inclusive": False,
        "category": "style",
        "gravity": 3.0,
        "importance": 3,
        "emoji": "🙄",
    },
    "speech": {
        "why": False,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "sports_terms": {
        "why": False,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "🏅",
    },
    "style": {
        "why": True,
        "inclusive": False,
        "category": "style",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "titles": {
        "why": True,
        "inclusive": False,
        "category": "gendered",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😟",
    },
    "transphobia": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
    "typography": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "❌",
    },
    "typos": {
        "why": False,
        "inclusive": False,
        "category": "orthography",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "❌",
    },
    "unconscious_bias": {
        "why": False,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "vision": {
        "why": True,
        "inclusive": False,
        "category": "unconscious_bias",
        "gravity": 2.0,
        "importance": 2,
        "emoji": "😒",
    },
    "xenophobia": {
        "why": True,
        "inclusive": False,
        "category": "openly_discriminating",
        "gravity": 1.0,
        "importance": 1,
        "emoji": "🚫",
    },
}
