name: languagetool
type: "java:8"

web:
  commands:
    start: |
      java -noverify -Xms1024M -Xmx1024M -XX:MaxMetaspaceSize=1024M -XX:+UseG1GC -XX:+UseStringDeduplication -cp languagetool-server.jar org.languagetool.server.HTTPServer --port $PORT --allow-origin "*"

disk: 2048

hooks:
    build: |
        export SERVER="languagetool-server.jar"
        export VERSION="5.5"
        export LT="LanguageTool"
        if [ ! -d "${PLATFORM_CACHE_DIR}/${LT}-${VERSION}" ]; then
          echo "Downloading ${LT} ${VERSION} ..."
          (
            cd "${PLATFORM_CACHE_DIR}"
            rm -rf "${LT}*"
            export FILE="${LT}-${VERSION}.zip"
            [ ! -f "$FILE" ] && curl -O https://languagetool.org/download/${FILE}
            unzip $FILE
            rm -rf $FILE
            cd ~
          )
        else
          echo "Using cached archive of ${LT} ${VERSION} ..."
        fi

        echo "Installing archive of ${LT} ${VERSION} ..."
        cp -R "${PLATFORM_CACHE_DIR}/${LT}-${VERSION}"/* .
