name: languagetool
type: "java:8"

disk: 2048

resources:
  base_memory: 1024
  memory_ratio: 1024

web:
  commands:
    start: |
      export MEMORY="$(jq ".info.limits.memory * 0.80 | tonumber | floor" /run/config.json)"
      java -noverify -Xms${MEMORY}M -Xmx${MEMORY}M -XX:+UseG1GC -XX:+UseStringDeduplication -cp languagetool-server.jar org.languagetool.server.HTTPServer --public --config server.properties --port $PORT --allow-origin "*"

hooks:
  build: |
    export SERVER="languagetool-server.jar"
    export VERSION="5.5"
    export LT="LanguageTool"
    if [ ! -d "${PLATFORM_CACHE_DIR}/${LT}-${VERSION}" ]; then
      echo "Downloading ${LT} ${VERSION} ..."
      (
        cd "${PLATFORM_CACHE_DIR}"
        rm -rf "${LT}*"
        export FILE="${LT}-${VERSION}.zip"
        [ ! -f "$FILE" ] && curl -O https://languagetool.org/download/${FILE}
        unzip $FILE
        rm -rf $FILE
        cd ~
      )
    else
      echo "Using cached archive of ${LT} ${VERSION} ..."
    fi

    echo "Installing archive of ${LT} ${VERSION} from '${PLATFORM_CACHE_DIR}/${LT}-${VERSION}' ..."
    cp -R "${PLATFORM_CACHE_DIR}/${LT}-${VERSION}"/* .

    sed "s/^#fasttext/fasttext/" server.properties > server.properties.fasttext
    mv server.properties.fasttext server.properties

    export FT_VERSION="0.9.2"
    export FT="fastText"
    export FT_DIR="${FT}-${FT_VERSION}"
    echo "Directory = ${FT_DIR}"
    if [ ! -d "${PLATFORM_CACHE_DIR}/${FT_DIR}" ]; then
    echo "Downloading ${FT} ${FT_VERSION} ..."
    (
      cd "${PLATFORM_CACHE_DIR}"
      rm -rf "${FT}*"
      export FT_FILE="v${FT_VERSION}.zip"
      [ ! -f "$FT_FILE" ] && curl -L https://github.com/facebookresearch/fastText/archive/refs/tags/${FT_FILE} --output ${FT_FILE}
      unzip $FT_FILE
      rm -rf $FT_FILE
      cd $FT_DIR
      make
      cd ~
      mkdir $FT
    )
    else
      echo "Using cached archive of ${FT} ${FT_VERSION} ..."
    fi
    echo "Installing archive of ${FT} ${FT_VERSION} from '${PLATFORM_CACHE_DIR}/${FT_DIR}' ..."
    cp -R "${PLATFORM_CACHE_DIR}/${FT_DIR}"/* ./"${FT}"

    export FT_MODEL="lid.176.bin"
    if [ ! -f "$FT_MODEL" ]; then
      echo "Download ${FT_MODEL} ..."
      curl https://dl.fbaipublicfiles.com/fasttext/supervised-models/${FT_MODEL} --output ${FT_MODEL}
    else
      echo "using ${FT_MODEL} model ..."
    fi
