maxTextLength=50000
cacheSize=3000
# 1. If you use one or more of English, French, German, Spanish, download ngram data from
# http://languagetool.org/download/ngram-data/ (English: en, French: fr, German: de, Spanish: es)
# 2. Unzip the ngram data files. If you have downloaded English and German, the content of this
# directory would be sub directories named „de“ and „en“.
#languageModel=/home/languagetool/ngram-data
pipelineCaching=true
maxPipelinePoolSize=500
pipelineExpireTimeInSeconds=3600
pipelinePrewarming=true
# maxCheckThreads=6 and maxWorkQueueSize=100 are good values for a server
# with 8 cores. For more cores, increase these values accordingly, e.g. double the number for
# 16 instead of 8 cores.
maxCheckThreads=3
maxWorkQueueSize=49
# fasttextModel and fasttextBinary should be set if your users check short texts
# (less than 50 characters per text). These options increase the accuracy of automatic language
# detection. Get the FastText binary and model from https://fasttext.cc.
fasttextModel=lid.176.ftz
fasttextBinary=fastText/fasttext
disabledRuleIds=DE_CASE,SEHR_GEEHRTER_NAME,LEERZEICHEN_HINTER_DOPPELPUNKT
