- name: "app"

  type: "python:3.11"

  container_profile: HIGHER_MEMORY
  initial_size: "0.5"

  web:
    upstream:
      socket_family: unix
    commands:
      start: |
        eval $(pdm venv activate in-project)
        FINAL_WORKER_COUNT=$(echo $PLATFORM_APPLICATION| base64 --decode | jq --argjson multiplier $MULTIPLIER '.resources.profile_size | tonumber |floor|2 * . |$multiplier * .|1 + . ')
        gunicorn app.main:app --preload -b unix:$SOCKET -w $FINAL_WORKER_COUNT -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*" --worker-tmp-dir="/run"

  hooks:
    build: |
      set -e

      ./install_dependencies.sh

      export FT_MODEL="lid.176.bin"

      if [ ! -f "${PLATFORM_CACHE_DIR}/$FT_MODEL" ]; then
        echo "Downloading ${FT_MODEL} ..."
        cd "${PLATFORM_CACHE_DIR}"
        curl https://dl.fbaipublicfiles.com/fasttext/supervised-models/${FT_MODEL} --output ${FT_MODEL}
        cd ~
      else
        echo "Using cached ${FT_MODEL} model ..."
      fi

      echo "Installing archive of ${FT_MODEL} from '${PLATFORM_CACHE_DIR}/${FT_MODEL}' ..."
      cp -R "${PLATFORM_CACHE_DIR}/${FT_MODEL}" ./training_data/.

      echo "e613bda316ecb4f5e1924140eedf81b81c087d9a *training_data/lid.176.bin" | sha1sum -c -

      ./compile-translations.sh

  crons:
    generate-statistics:
      spec: "0 1 * * 0"
      cmd: |
        if [ "$PLATFORM_BRANCH" = main ]; then
            ./statistics.sh -l en-US
            ./statistics.sh -l de
        fi
    analyze-rules:
      spec: "0 1 * * *"
      cmd: |
        if [ "$PLATFORM_BRANCH" = dev ]; then
            ./analyze_rules.sh -l en
            ./analyze_rules.sh -l de
        fi

  mounts:
    "files":
      source: service
      service: files
      source_path: files

  relationships:
    rediscache: "rediscache:redis"
    languagetool: "languagetool:http"
