- name: "english"

  variables:
    env:
      LANGS: '["en"]'
      LANGUAGE_ENDPOINT_ENABLED_EN: true

  type: "python:3.11"

  disk: 2048

  resources:
    base_memory: 1024
    memory_ratio: 1024

  container_profile: LOW_MEMORY

  web:
    upstream:
      socket_family: unix
    commands:
      start: |
        FINAL_WORKER_COUNT=$(./compute_worker_count.sh -t $THREADS_EN -a $PLATFORM_APPLICATION | head -n 1)
        blackfire-python gunicorn app.main:app --preload -b unix:$SOCKET -w $FINAL_WORKER_COUNT --threads ${THREADS_EN} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"

  hooks: &hooks
    build: |
      set -e
      du -sh $PLATFORM_CACHE_DIR
      mkdir -p $HOME/.global
      mkdir -p $HOME/.venv
      mkdir -p $PLATFORM_CACHE_DIR/.global 
      mkdir -p $PLATFORM_CACHE_DIR/.venv
      echo "Restoring from  build cache"
      rsync -ar $PLATFORM_CACHE_DIR/.venv/ $HOME/.venv
      rsync -ar $PLATFORM_CACHE_DIR/.global/ $HOME/.global
      echo "Done restoring from build cache"
      echo "Installing pdm and pdm dependecies"
      pip install pdm
      pdm config install.cache True
      pdm config cache_dir $PLATFORM_CACHE_DIR/pdm
      pdm run python -m ensurepip --upgrade
      pdm install
      # We need to asure we allow --user installs which is why we modify the venv configuration.
      sed -i 's/include-system-site-packages\ =\ false/include-system-site-packages\ =\ true/' .venv/pyvenv.cfg
      #SPACY_RELEASE=$(curl --silent "https://api.github.com/repos/explosion/spaCy/releases/latest" | jq -r .tag_name | sed -r 's/^.{1}//')
      # We are locking spacy for the time being.
      SPACY_RELEASE=3.5.0
      echo "Downloading en_core_web_md-$SPACY_RELEASE"
      wget -nc https://github.com/explosion/spacy-models/releases/download/en_core_web_md-$SPACY_RELEASE.tar.gz -O $PLATFORM_CACHE_DIR/en_core_web_md-$SPACY_RELEASE.tar.gz
      pdm install $PLATFORM_CACHE_DIR/en_core_web_md-$SPACY_RELEASE.tar.gz
      #pdm run python -m spacy download en_core_web_md-$SPACY_RELEASE --direct
      echo "Downloading en_core_web_md-$SPACY_RELEASE"
      wget -nc https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-$SPACY_RELEASE.tar.gz -O $PLATFORM_CACHE_DIR/en_core_web_md-$SPACY_RELEASE.tar.gz
      pdm install $PLATFORM_CACHE_DIR/de_core_news_lg-$SPACY_RELEASE.tar.gz
      #pdm run python -m spacy download de_core_news_lg-$SPACY_RELEASE --direct
      echo "Pybabel compile"
      pdm run pybabel compile -d locales -l en_US -f
      pdm run pybabel compile -d locales -l en_GB -f
      pdm run pybabel compile -d locales -l de_DE -f
      pdm run pybabel compile -d locales -l de_AT -f
      pdm run pybabel compile -d locales -l de_CH -f
      echo "Saving to build cache"
      rsync -ar $HOME/.venv/ $PLATFORM_CACHE_DIR/.venv
      rsync -ar $HOME/.global/ $PLATFORM_CACHE_DIR/.global
      echo "Done saving to build cache"
  crons:
    generate-statistics:
      spec: "0 1 * * 0"
      cmd: |
        if [ "$PLATFORM_BRANCH" = main ]; then
            ./statistics.sh -l=en-US
        fi
    analyze-rules:
      spec: "0 1 * * *"
      cmd: |
        if [ "$PLATFORM_BRANCH" = dev ]; then
            ./analyze_rules.sh -l=en
        fi

  mounts:
    "analyze_rules": "shared:files/analyze_rules"

- name: "german"

  variables:
    env:
      LANGS: '["de"]'
      LANGUAGE_ENDPOINT_ENABLED_DE: true

  type: "python:3.11"

  disk: 2048

  resources:
    base_memory: 1024
    memory_ratio: 1024

  container_profile: BALANCED

  dependencies:
    python3:
      pdm: "*"

  web:
    upstream:
      socket_family: unix
    commands:
      start: |
        FINAL_WORKER_COUNT=$(./compute_worker_count.sh -t $THREADS_DE -a $PLATFORM_APPLICATION | head -n 1)
        blackfire-python gunicorn app.main:app --preload -b unix:$SOCKET -w $FINAL_WORKER_COUNT --threads ${THREADS_DE} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"

  hooks:
    <<: *hooks

  crons:
    generate-statistics:
      spec: "0 1 * * 0"
      cmd: |
        if [ "$PLATFORM_BRANCH" = main ]; then
            ./statistics.sh -l=de-DE
        fi
    analyze-rules:
      spec: "0 1 * * *"
      cmd: |
        if [ "$PLATFORM_BRANCH" = dev ]; then
            ./analyze_rules.sh -l=de
        fi

  mounts:
    "analyze_rules": "shared:files/analyze_rules"

- name: "app"

  variables:
    env:
      MODELS: "[]"

  type: "python:3.11"

  disk: 2048

  resources:
    base_memory: 1024
    memory_ratio: 1024

  container_profile: LOW_MEMORY

  web:
    upstream:
      socket_family: unix
    commands:
      start: |
        FINAL_WORKER_COUNT=$(./compute_worker_count.sh -t $THREADS -a $PLATFORM_APPLICATION | head -n 1)
        blackfire-python gunicorn app.main:app --preload -b unix:$SOCKET -w $FINAL_WORKER_COUNT --threads ${THREADS} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"

  hooks:
    <<: *hooks
    build: |
      set -e

      export FT_MODEL="lid.176.bin"

      if [ ! -f "${PLATFORM_CACHE_DIR}/$FT_MODEL" ]; then
        echo "Downloading ${FT_MODEL} ..."
        cd "${PLATFORM_CACHE_DIR}"
        curl https://dl.fbaipublicfiles.com/fasttext/supervised-models/${FT_MODEL} --output ${FT_MODEL}
        cd ~
      else
        echo "Using cached ${FT_MODEL} model ..."
      fi

      echo "Installing archive of ${FT_MODEL} from '${PLATFORM_CACHE_DIR}/${FT_MODEL}' ..."
      cp -R "${PLATFORM_CACHE_DIR}/${FT_MODEL}" ./training_data/.

      echo "e613bda316ecb4f5e1924140eedf81b81c087d9a *training_data/lid.176.bin" | sha1sum -c -

  relationships:
    rediscache: "rediscache:redis"
    de: "german:http"
    en: "english:http"
