- name: "english"

  variables:
    env:
      LANGS: '["en"]'
      LANGUAGE_ENDPOINT_ENABLED_EN: true

  type: "python:3.11"

  disk: 2048

  resources:
    base_memory: 1024
    memory_ratio: 1024

  container_profile: LOW_MEMORY

  dependencies:
    python3:
      pipenv: "2023.2.4"

  web:
    upstream:
      socket_family: unix
    commands:
      start: |
        FINAL_WORKER_COUNT=$(./compute_worker_count.sh -t $THREADS_EN -a $PLATFORM_APPLICATION | head -n 1)
        blackfire-python gunicorn app.main:app --preload -b unix:$SOCKET -w $FINAL_WORKER_COUNT --threads ${THREADS_EN} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"

  hooks: &hooks
    build: |
      set -e

      mkdir -p $HOME/.local
      mkdir -p $PLATFORM_CACHE_DIR/.local
      mkdir -p $HOME/.global
      mkdir -p $PLATFORM_CACHE_DIR/.global

      rsync -ar $PLATFORM_CACHE_DIR/.local $HOME/.local
      rsync -ar $PLATFORM_CACHE_DIR/.global $HOME/.global

      pipenv install --system --deploy

      pipenv run /opt/python/3.11/bin/python3.11 -m spacy download en_core_web_md
      pipenv run /opt/python/3.11/bin/python3.11 -m spacy download de_core_news_lg

      pipenv run pybabel compile -d locales -l en_US -f
      pipenv run pybabel compile -d locales -l en_GB -f
      pipenv run pybabel compile -d locales -l de_DE -f
      pipenv run pybabel compile -d locales -l de_AT -f
      pipenv run pybabel compile -d locales -l de_CH -f

      rsync -ar $HOME/.local $PLATFORM_CACHE_DIR/.local
      rsync -ar $HOME/.global $PLATFORM_CACHE_DIR/.global

  crons:
    generate-statistics:
      spec: "0 1 * * 0"
      cmd: |
        if [ "$PLATFORM_BRANCH" = main ]; then
            ./statistics.sh -l=en-US
        fi
    analyze-rules:
      spec: "0 1 * * *"
      cmd: |
        if [ "$PLATFORM_BRANCH" = dev ]; then
            ./analyze_rules.sh -l=en
        fi

  mounts:
    "analyze_rules": "shared:files/analyze_rules"

- name: "german"

  variables:
    env:
      LANGS: '["de"]'
      LANGUAGE_ENDPOINT_ENABLED_DE: true

  type: "python:3.11"

  disk: 2048

  resources:
    base_memory: 1024
    memory_ratio: 1024

  container_profile: BALANCED

  dependencies:
    python3:
      pipenv: "2023.2.4"

  web:
    upstream:
      socket_family: unix
    commands:
      start: |
        FINAL_WORKER_COUNT=$(./compute_worker_count.sh -t $THREADS_DE -a $PLATFORM_APPLICATION | head -n 1)
        blackfire-python gunicorn app.main:app --preload -b unix:$SOCKET -w $FINAL_WORKER_COUNT --threads ${THREADS_DE} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"

  hooks:
    <<: *hooks

  crons:
    generate-statistics:
      spec: "0 1 * * 0"
      cmd: |
        if [ "$PLATFORM_BRANCH" = main ]; then
            ./statistics.sh -l=de-DE
        fi
    analyze-rules:
      spec: "0 1 * * *"
      cmd: |
        if [ "$PLATFORM_BRANCH" = dev ]; then
            ./analyze_rules.sh -l=de
        fi

  mounts:
    "analyze_rules": "shared:files/analyze_rules"

- name: "app"

  variables:
    env:
      MODELS: "[]"

  type: "python:3.11"

  disk: 2048

  resources:
    base_memory: 1024
    memory_ratio: 1024

  container_profile: LOW_MEMORY

  dependencies:
    python3:
      pipenv: "2023.2.4"

  web:
    upstream:
      socket_family: unix
    commands:
      start: |
        FINAL_WORKER_COUNT=$(./compute_worker_count.sh -t $THREADS -a $PLATFORM_APPLICATION | head -n 1)
        blackfire-python gunicorn app.main:app --preload -b unix:$SOCKET -w $FINAL_WORKER_COUNT --threads ${THREADS} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*"

  hooks:
    <<: *hooks
    build: |
      set -e

      export FT_MODEL="lid.176.bin"

      if [ ! -f "${PLATFORM_CACHE_DIR}/$FT_MODEL" ]; then
        echo "Downloading ${FT_MODEL} ..."
        cd "${PLATFORM_CACHE_DIR}"
        curl https://dl.fbaipublicfiles.com/fasttext/supervised-models/${FT_MODEL} --output ${FT_MODEL}
        cd ~
      else
        echo "Using cached ${FT_MODEL} model ..."
      fi

      echo "Installing archive of ${FT_MODEL} from '${PLATFORM_CACHE_DIR}/${FT_MODEL}' ..."
      cp -R "${PLATFORM_CACHE_DIR}/${FT_MODEL}" ./training_data/.

      echo "e613bda316ecb4f5e1924140eedf81b81c087d9a *training_data/lid.176.bin" | sha1sum -c -

  relationships:
    rediscache: "rediscache:redis"
    de: "german:http"
    en: "english:http"
