on: [push]
name: Build a Docker image and Push it to ACR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pdm sync

      - name: Install FastText models
        if: steps.cache-fasttext.outputs.cache-hit != 'true'
        run: |
          wget -P training_data https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin

      - name: Compile translation
        run: |
          pdm run pybabel compile -d locales -l de_DE -f
          pdm run pybabel compile -d locales -l de_AT -f
          pdm run pybabel compile -d locales -l de_CH -f
          pdm run pybabel compile -d locales -l en_US -f
          pdm run pybabel compile -d locales -l en_GB -f

      - name: Update requirements.txt for Docker image
        run: |
          pdm export --prod -o requirements.txt

      # build nlp api
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }}
          # release version
          ref=${{ github.ref_name }}
          tag=${ref////-}
          echo $tag
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:$tag
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:$tag
