name: Deploy to Massdriver
on:
  push:
    branches: [main]

jobs:
  push_and_deploy:
    runs-on: ubuntu-latest
    env:
      MASSDRIVER_ORG_ID: ${{ secrets.MASSDRIVER_ORG_ID }}
      MASSDRIVER_API_KEY: ${{ secrets.MASSDRIVER_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pdm sync

      - name: Install FastText models
        if: steps.cache-fasttext.outputs.cache-hit != 'true'
        run: |
          wget -P training_data https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin

      - name: Update requirements.txt for Docker image
        run: |
          pdm export --prod -o requirements.txt --without-hashes

      - name: Install Massdriver CLI
        uses: massdriver-cloud/actions@v3

      - name: Push Image
        uses: massdriver-cloud/actions/image_push@v3
        with:
          namespace: wittyworks
          image-name: nlpapi
          artifact: ${{ secrets.AUTHENTICATION_ARTIFACT_ID }}
          region: westeurope
          image-tag: "main-${{ github.sha }}"

      - name: Publish Bundle
        uses: massdriver-cloud/actions/bundle_publish@v3
        with:
          build-directory: ./massdriver

      - name: Set Image Version
        uses: massdriver-cloud/actions/app_patch@v3
        with:
          project: nlpapi
          target: main
          manifest: nlpapi
          set: |
            .image.tag = "main-${{ github.sha }}"

      - name: Deploy App
        uses: massdriver-cloud/actions/app_deploy@v3
        with:
          project: nlpapi
          target: main
          manifest: nlpapi
