on: [push]
name: Build a Docker image and Push it to ACR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pdm
        run: |
          python -m pip install --upgrade pdm wheel

      - name: Update requirements.txt for Docker image
        run: |
          pdm export --prod -o requirements.txt

      - name: Compile translation
        run: |
          ./compile-translations.sh

      # build nlp api
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }}
          # release version
          ref=${{ github.ref_name }}
          tag=${ref////-}
          echo $tag
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:$tag
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:$tag
