name: run tests

on: [push]

env:
  #CONTEXT_CHECKER_URL: "https://setfit-english.westeurope.inference.ml.azure.com/score"
  CONTEXT_CHECKER_API_KEY: ${{ secrets.CONTEXT_CHECKER_API_KEY }}
  #CONTEXT_CHECKER_URL_DE: "https://setfit-german.westeurope.inference.ml.azure.com/score"
  CONTEXT_CHECKER_API_KEY_DE: ${{ secrets.CONTEXT_CHECKER_API_KEY_DE }}
  AADB2C_TENANT_ID: "81932fe1-f25e-43fc-b674-002ff8235389"
  AADB2C_CLIENT_ID: "7e090308-575a-4e7d-84e4-78c83d083ab6"
  AADB2C_EXPECTED_SCOPE: "access_as_user"
  AADB2C_DOMAIN: "wittyworksdev"
  AADB2C_POLICY: "B2C_1A_SIGNUP_SIGNIN"
  AADB2C_RSA_KID: "CzwYIHE24nhDSSvHaOZqiSpLUxRAWf9nCi2tKg1tB0M"
  AADB2C_RSA_N: "vb24oUNTgKnzBuN2WXuBAzIucW4Bt0HVo6KeCl0oNPEO9K1pH10_IAPhRO8bC2cdERmSH0tDaNnN5WbXTGV8aiNN5rcrezTlcjmZay4WZj0CrURUNuYAdxz_vPtbfnRiPOz_Sgo2v0ed6hjxLGY3J6Mt4EMP_AWhmx6LMFmQbCslZzBo4pzhmQ36oey05yFvyzPMuuH51USWGcpBPIFqVrlMfXcb0Lel6JPgff4OU14lkCsY4UB9AXVu4JRWbAaq_cFZIZK-v6RLZx3Msu3r9wWOa0UKXnWMCTf936rJAEXUOwNW52CWlt3pyMjHY9rs_uUTskDFrsLQ7s7rHhweZQ"
  OFFICE_SSO_TENANT_ID: "7bd22e84-34b1-4b7b-b6f7-4cd7da0a5e4a"
  OFFICE_SSO_CLIENT_ID: "3117be5a-3323-453f-810d-8795bac7f31d"
  OFFICE_SSO_EXPECTED_SCOPE: "access_as_user"
  OFFICE_SSO_RSA_KID: "-KI3Q9nNR7bRofxmeZoXqbHZGew"
  OFFICE_SSO_RSA_N: "tJL6Wr2JUsxLyNezPQh1J6zn6wSoDAhgRYSDkaMuEHy75VikiB8wg25WuR96gdMpookdlRvh7SnRvtjQN9b5m4zJCMpSRcJ5DuXl4mcd7Cg3Zp1C5-JmMq8J7m7OS9HpUQbA1yhtCHqP7XA4UnQI28J-TnGiAa3viPLlq0663Cq6hQw7jYo5yNjdJcV5-FS-xNV7UHR4zAMRruMUHxte1IZJzbJmxjKoEjJwDTtcd6DkI3yrkmYt8GdQmu0YBHTJSZiz-M10CY3LbvLzf-tbBNKQ_gfnGGKF7MvRCmPA_YF_APynrIG7p4vPDRXhpG3_CIt317NyvGoIwiv0At83kQ"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pdm sync

      - name: Caching FastText models
        id: cache-fasttext
        uses: actions/cache@v3
        env:
          cache-name: cache-fasttext
        with:
          path: ./training_data/lid.176.bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./training_data/lid.176.bin') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install FastText models
        if: steps.cache-fasttext.outputs.cache-hit != 'true'
        run: |
          wget -P training_data https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin

      - if: startsWith(github.ref, 'refs/tags/') != true && github.ref != 'refs/heads/main'
        name: Use LT "dev" via .env file for anything but "main"
        run: |
          echo "LANGUAGETOOL_API=\"https://lt.dev-54ta5gq-jyeciedibdzvq.fr-4.platformsh.site/v2\"" >> .env

      - name: Run test suite
        run: |
          export testing=True
          pdm run pytest --cov-config .coveragerc --cov=app -vv --cov-report=xml --cov-report=html

      - name: Override Coverage Source Path for Sonar
        run: |
          sed -i "s/<source>\/home\/runner\/work\/nlp_api\/nlp_api\/app<\/source>/<source>\/github\/workspace\/app<\/source>/g" /home/runner/work/nlp_api/nlp_api/coverage.xml
          sed -i "s/<source>\/home\/runner\/work\/nlp_api\/nlp_api\/bin<\/source>/<source>\/github\/workspace\/bin<\/source>/g" /home/runner/work/nlp_api/nlp_api/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
