name: NLP API

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
          pipenv run python -m spacy download en_core_web_sm
          pipenv run python -m spacy download de_core_news_sm

      - id: cache-mo-files
        uses: actions/cache@v1
        with:
          path: ./locales
          key: ${{ runner.os }}-mo-files-${{ hashFiles('**/*.mo') }}

      - name: Compile translation
        if: steps.cache-mo-files.outputs.cache-hit != 'true'
        run: |
          pipenv run pybabel compile -d locales -l de_DE -f
          pipenv run pybabel compile -d locales -l en_GB -f

      - name: Run test suite
        run: |
          pipenv run pytest --cov-config .coveragerc --cov=app